### ISSUE TITLE
No hard-coding of grammars and databases in the Haskell source code

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#57]
The goal of MULLE is to have a tool that anyone can install without any knowledge of Haskell. 

So, the info in the following files should be moved to some kind of config files:

- `muste-ajax/app/DbInit/Data.hs`
- `muste/src/Muste/Grammar/Grammars.hs`

Additionally, it would be nice if the tests and benchmarks could load their tests from a config file.

**Comment by heatherleaf** [comment]
I like yaml myself. And it could look something like this:

```
grammars:
  Prima: novo_modo/Prima.pgf    # path to grammar file
  Secunda: novo_modo/Secunda.pgf
  Exemplum: exemplum/Exemplum.pgf

languages:
  ExemplumAra:
    direction: rtl  # default ltr
  ExemplumChi: 
    spacing: 50%  # default 100%

# lessons are ordered - they have to be shown in some order in the GUI
lessons:
- name: PrimaLatSwe
  description: Lesson 1 from Novo Modo
  grammar: Prima
  srcLang: PrimaLat
  trgLang: PrimaSwe
  # sizeLimit: 3  # default value: null
  depthLimit: 3  # default value: null
  # enabled: true  # default value
  repeatable: false  # default value: true
- name: ExemplumEngAra
  description: Example lesson English-Arabic
  grammar: Exemplum
  srcLang: ExemplumEng
  trgLang: ExemplumAra
  sizeLimit: 3

# exercises are based on basic lesson keys
PrimaLatSwe:
- ["vinum sapiens est", "han är vis"]
- ["Augustus imperium tenet" , "imperatorn håller riket"]
- - Augustus felix est
  - vännen är lycklig

ExemplumEngAra:
- - many kings love Paris
  -  يَقْرَأُ مَلِكٌ جوَيِّدٌ كِتابً 
- - ...
  - ...
```
