### ISSUE TITLE
Simplify backend database

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#97]
Remove static information from the SQL database, i.e., information that is already in the lesson configuration file.

This means that the following information should be removed from the database:

```
- name: "Swedish"
  key: 1
  search-options:
    size: 7
  settings:
    highlight-matches: on
  grammar: "grammars/exemplum/Exemplum.pgf"
  languages:
    source: "ExemplumEng"
    target: "ExemplumSwe"
  exercises:
    - source: "many kings love Paris"
      target: "en god kung älskar Paris"
    - source: "good kings don't read books"
      target: "en god kung läser en bok"
    - source: "the king reads a book in Paris"
      target: "en kung läser en bok"
    - source: "a king reads a good book"
      target: "en kung i Paris läser en bok"
```

This implies some changes to the frontend too - that information has to be remembered by the frontend over the session.
